# Generated by Django 4.2.7 on 2025-09-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255, verbose_name='Från')),
                ('end_location', models.CharField(max_length=255, verbose_name='Till')),
                ('date', models.DateField(verbose_name='Datum')),
                ('time', models.TimeField(verbose_name='Tid')),
                ('name', models.CharField(max_length=100, verbose_name='Namn')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefonnummer')),
                ('status', models.CharField(choices=[('pending', 'Väntar'), ('accepted', 'Accepterad'), ('declined', 'Avböjd')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Skapad')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Uppdaterad')),
            ],
            options={
                'verbose_name': 'Bokning',
                'verbose_name_plural': 'Bokningar',
                'ordering': ['-created_at'],
            },
        ),
    ]
