# Generated by Django 4.2.7 on 2025-09-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-post'),
            preserve_default=False,
        ),
    ]
